name: sc_project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - pandas
  - matplotlib
  - seaborn
  - pyyaml
  - pip:
      - scanpy
      - python-igraph
      - louvain
      - leidenalg