name: sc_lung_project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - scanpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - python-igraph
  - louvain
  - leidenalg
  - jupyterlab
  - ipympl
  - nodejs
  - pip
  - pip:
    - scanpy[leiden]